name: Tạo

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Nhập mã'
        required: true
      pincode:
        description: 'Mã pin'
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes:240
    steps:
    - uses: actions/checkout@v3
    - name: Tải giao diện
      run: echo Đang tải... &&& sudo apt update &>/dev/null && sudo apt upgrade -y &>/dev/null && sudo apt install ubuntu-desktop -y &>/dev/null 
    - name: Cài đặt remote desktop
      run: |
          echo Đang cài đặt...
          wget -O remote.deb https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb &>/dev/null 
          sudo apt install ./remote.deb -y &>/dev/null 
          echo Đang lấy token...
    - name: Lấy token
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Thành công!
      run: |
          echo Bạn đã cài đặt thành công!
          echo Hãy sử dụng vui vẻ nhé!
          echo Đang loops....
          tail -f
          yes &>/dev/null
